### ISSUE TITLE
Multi-line OCR result crashes logs window

### ISSUE THREAD

**Issue by stevejackson** [mathewthe2/Game2Text#14]
# Platform/version

`main` branch, Apr 23 2021. MacOS 11.1, Chrome.

Using Space OCR EU.

# Bug reproduction

OCR'd this:

<img width="626" alt="Screen Shot 2021-04-23 at 4 18 39 AM" src="https://user-images.githubusercontent.com/949576/115841632-fe5b4080-a3ea-11eb-8260-ca3cb7a344cd.png">

It results in OCR with multiple lines of text (it has line breaks):

<img width="369" alt="Screen Shot 2021-04-23 at 4 19 28 AM" src="https://user-images.githubusercontent.com/949576/115841730-19c64b80-a3eb-11eb-86d9-39ca35f5b331.png">

Looks like this in the logs/text file:

```
20210423-041552, 「城下町はあの門を越えた先た。
ジャマな門番には金を握らせるな・・
だガ旅立ら前に計な出費は避けをいな。
```

It causes this error when logs panel is opened up:

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/steven/dev/Game2Text/logger.py", line 65, in log_video_image
    insert_newest_log_with_image(base64_image, os.path.splitext(image_path)[1])
  File "/Users/steven/dev/Game2Text/logger.py", line 143, in insert_newest_log_with_image
    saved_logs = get_logs()
  File "/Users/steven/dev/Game2Text/logger.py", line 125, in get_logs
    date = parse_time_string(log_id)
  File "/Users/steven/dev/Game2Text/logger.py", line 24, in parse_time_string
    return datetime.strptime(time_string, '%Y%m%d-%H%M%S')
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'ジャマな門番には金き握らせるな' does not match format '%Y%m%d-%H%M%S'
```

## Likely cause

I think it's expecting all log entries to be a single line. We could fix this to be on a single line, or else change the logger format.

**Comment by mathewthe2** [comment]
This seems like a problem unique to the return result from OCR space. We could parse the results in ocr_space.py so they could be on one line.
