### ISSUE TITLE
Read-only file system error on mac

### ISSUE THREAD

**Issue by gustanas** [mathewthe2/Game2Text#45]
Hey, the app doesn't seem to work on macs (intel-based). I got the following error when circling a text.

```
gustavo@Gustavos-MacBook-Pro ~ % /var/folders/2k/0r_v629x3311ndhjl8z6w3_c0000gn/T/AppTranslocation/7E4897D4-9A2E-4DB4-B758-3C5CAC8A30BF/d/game2text.app/Contents/MacOS/game2text ; exit;
Error: cannot record audio with selected device [Errno -9981] Input overflowed
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "eel/__init__.py", line 259, in _process_message
  File "game2text.py", line 32, in recognize_image
  File "ocr.py", line 19, in detect_and_log
  File "ocr.py", line 35, in image_to_text
  File "util.py", line 57, in base64_to_image
  File "util.py", line 63, in base64_to_image_path
OSError: [Errno 30] Read-only file system: '/private/var/folders/2k/0r_v629x3311ndhjl8z6w3_c0000gn/T/AppTranslocation/7E4897D4-9A2E-4DB4-B758-3C5CAC8A30BF/d/game2text.app/Contents/MacOS/logs/images/temp.png'
2022-09-07T13:48:05Z <Greenlet at 0x7fec218d2050: _process_message({'call': 31.43319692611729, 'name': 'recognize_ima, <geventwebsocket.websocket.WebSocket object at 0x7)> failed with OSError
```

**Comment by mathewthe2** [comment]
You need to move it to the applications folder.

**Comment by gustanas** [comment]
Ooh I can't believe I missed something that obvious! Thanks a lot
